export const clubs = [
    "Achilles 1894",
    "VV Actief",
    "ACV",
    "MVV Alcides",
    "FC Amboina",
    "SC Angelslo",
    "VV Annen",
    "FC Assen",
    "Asser Boys",
    "VV Bargeres",
    "VV Beilen",
    "VV BEW",
    "SV Borger",
    "BSVV",
    "VV Buinen",
    "VV Buinerveen",
    "VV CEC",
    "CSVC",
    "VV Dalen",
    "VV Diever-Wapse",
    "DOS '63",
    "VV Drenthina",
    "DSC '65",
    "DVC '59",
    "DVSV",
    "VV Dwingeloo",
    "DZOH",
    "EEC",
    "SV Een",
    "VV Eext",
    "VV EHS '85",
    "SC Elim",
    "VV Emmen",
    "Erica '86",
    "SC Erica",
    "VV FDS",
    "CVV Fit Boys",
    "VV Gasselternijveen",
    "CVV Germanicus",
    "VV Gieten",
    "Vv Gieterveen",
    "VV GKC",
    "VV GOMOS",
    "VV Havelte",
    "HHCombi",
    "VV HOC",
    "SV HODO",
    "VV Hollandscheveld",
    "SV Hoogersmilde",
    "VV Hoogeveen",
    "HZVV",
    "VV Klazienaveen",
    "VV KSC",
    "LTC",
    "VV LEO",
    "FC Meppel",
    "MSC",
    "SV Nieuw Balinge",
    "VV Nieuw Buinen",
    "VV Nieuw Roden",
    "NKVV",
    "VV Noordscheschut",
    "NWVV",
    "Old Forward",
    "ONR",
    "VV Peize",
    "SV Pesse",
    "VV Protos",
    "VV Raptim",
    "VV Roden",
    "VV Rolder Boys",
    "SC Roswinkel",
    "VV Ruinen",
    "VV Ruinerwold",
    "VV Schoonebeek",
    "SCN",
    "SGO",
    "VV Sleen",
    "VV Smilde '94",
    "VV SVBC",
    "VV SVBO",
    "SVDB",
    "SVN '69",
    "SVV '04",
    "SVZ",
    "TEVV",
    "VV Tiendeveen",
    "VV Titan",
    "SV Twedo",
    "SV Tynaarlo",
    "VV Uffelte",
    "VV VAKO",
    "Valther Boys",
    "VV Valthermond",
    "VCG",
    "VV Veenhuizen",
    "VV VEV",
    "VIOS Oosterhesselen",
    "VV Vitesse '63",
    "VV VKW",
    "VVAK",
    "VV Wacker-van Dijk",
    "VV Wapserveen",
    "VV Weerdinge",
    "VV de Weide",
    "Weiteveense Boys",
    "VV Wijster",
    "Witteveense Boys '87",
    "WKE '16",
    "SV Yde de Punt",
    "VV Zandpol",
    "VV ZBC",
    "FC Zuidlaren",
    "VV Zuidlaarderveen",
    "VV Zuidwolde",
    "VV Zwartemeer",
    "SC Zwartemeerse Boys",
    "SP Zweeloo",
    "ZZVV",
    "FC Almere",
    "VV AS '80",
    "ASV Dronten",
    "SC Bant",
    "BAS-Voetbal",
    "SV Batavia '90",
    "SC Buitenboys",
    "SC Creil",
    "SC Emmeloord",
    "SV Ens",
    "SC Espel",
    "Flevo Boys",
    "Forza Almere",
    "FC Kraggenburg",
    "SV Lelystad '67",
    "VV Nagele",
    "Reaal Dronten",
    "RKO",
    "Sporting Almere",
    "SVM Marknesse",
    "Swift '64",
    "VV Tollebeek",
    "SV TONEGO",
    "VV Unicum",
    "SV Urk",
    "ASC Waterwijk",
    "VV Zeewolde",
    "VV Aengwirden",
    "VV Akkrum",
    "SC Amelandia",
    "VV Anjum",
    "VV Arum",
    "ASC '75",
    "AVC",
    "AVV",
    "RKVV Bakhuizen",
    "VV Bakkeveen",
    "VV Balk",
    "Be Quick Dokkum",
    "VV Beetgum",
    "FC Burgum",
    "SC Berlikum",
    "FC Birdaard",
    "VV Black Boys",
    "CVV Blauw Wit '34",
    "VV Blauwhuis",
    "VV De Blesse",
    "VV Blija",
    "VV Blue Boys",
    "SC Bolsward",
    "SC Boornbergum '80",
    "Broekster Boys",
    "VV Buitenpost",
    "VV CVO",
    "CVVO",
    "VV Delfstrahuizen",
    "DIO Oosterwolde",
    "VV Dokkum",
    "SV Donkerbroek",
    "VV Drachten",
    "Drachtster Boys",
    "VV Drogeham",
    "VV Dronrijp",
    "VV DTD",
    "DWP",
    "VV Eastermar",
    "VV EBC",
    "'t Fean '58",
    "FFS",
    "SC Flamingo",
    "VV Foarút",
    "FC Fochteloo",
    "SC Franeker",
    "Friese Boys",
    "FVC",
    "GAVC",
    "VV Geel Wit",
    "VV Gersloot",
    "VV Gorredijk",
    "SV De Griffioen",
    "GSVV",
    "VV Hardegarijp",
    "VV Harkema-Opeinde",
    "Harkemase Boys",
    "FC Harlingen",
    "SV Haulerwijk",
    "VV Heeg",
    "VV Heerenveen",
    "Heerenveense Boys",
    "SV Hielpen",
    "VV HJSC",
    "VV Holwerd",
    "SV Houtigehage",
    "IJ.V.C.",
    "VV Irnsum",
    "VV Jistrum",
    "SC Joure",
    "VV Jubbega",
    "VV Kollum",
    "SC Kootstertille",
    "LAC Frisia 1883",
    "VV Langezwaag",
    "VV Langweer",
    "VV de Lauwers",
    "Leeuwarder Zwaluwen",
    "VV Lemmer",
    "SC Leovardia",
    "SC Lions '66",
    "LSC 1890",
    "LVV Friesland",
    "Sportclub Makkinga",
    "VV Makkum",
    "VV Marrum",
    "VV Mildam",
    "VV Minnertsga",
    "RKVV MKV '29",
    "VV De Monnik",
    "SV Mulier",
    "VV Nicator",
    "VV Nieuweschoot",
    "VV Nijland",
    "NOK",
    "VV Noordbergum",
    "VV ODV",
    "VV Oerterp",
    "SV Oeverzwaluwen",
    "VV Oldeboorn",
    "VV Oldeholtpade",
    "Olyphia",
    "VV ONB",
    "ONS Sneek",
    "ONT",
    "VV Oostergo",
    "VV Oosterlittens",
    "VV Oosterstreek",
    "VV Oudega",
    "VV Oudehaske",
    "VV Ouwe Syl",
    "VV QVC",
    "VV Read Swart",
    "Renado",
    "VV Rijperkerk",
    "Ropta Boys",
    "VV Rottevalle",
    "SV RWF",
    "VV Scharnegoutum '70",
    "VV SDS",
    "VV Sint Annaparochie",
    "Sint Jacob",
    "VV Sleat",
    "VV Sneek Wit Zwart",
    "Sparta '59",
    "VV Sport Vereent",
    "SSS '68",
    "VV Stânfries",
    "SC Stiens",
    "VV Suameer",
    "SV Suawoude",
    "VV Surhuisterveen",
    "VV De Sweach",
    "VV Ternaard",
    "SC Terschelling",
    "VV TFS",
    "SV THOR",
    "VV Tijnje",
    "VV TOP '63",
    "VV Trinitas",
    "VC Trynwâlden",
    "SC Twijzel",
    "VV Tzum",
    "VV Tzummarum",
    "UDIROS",
    "V en V '68",
    "VCR",
    "SC Veenwouden",
    "VV VIOD (Driesum)",
    "VVI",
    "VVT",
    "VWC",
    "SV de Wâlde",
    "VV de Wâlden",
    "VV Wardy",
    "VV Warga",
    "VV Waskemeer",
    "VV Waterpoort Boys",
    "VV Wispolia",
    "FC Wolvega",
    "VV Workum",
    "VV Woudsend",
    "WTOC",
    "WWS",
    "Wykels Hallum",
    "VV Zandhuizen",
    "ZMVV Zeerobben",
    "VV Zwaagwesteinde",
    "AAC/Olympia",
    "Achilles '29",
    "VV Activia",
    "AD '69",
    "VV Advendo '57",
    "Ajax Breedenbroek",
    "UVV Albatross",
    "VV Alem",
    "Alexandria",
    "SV Almen",
    "VV Alverna",
    "Anadolu '90",
    "SV Angeren",
    "Angerlo Vooruit",
    "CSV Apeldoorn",
    "ASV Apeldoornse Boys",
    "Aquila",
    "VV Arnhemia",
    "Arnhemse Boys",
    "ASH",
    "VV Asperen",
    "AVIOS",
    "AVW '66",
    "SV AWC",
    "AZ 2000",
    "AZC Zutphen",
    "AZSV",
    "SV Babberich",
    "VV Barneveld",
    "SV Basteom",
    "Vv de Bataven",
    "VV Batavia",
    "ZVV Be Quick",
    "SV Beatrix",
    "VV Beekbergen",
    "VV Beesd",
    "Sportclub Bemmel",
    "VV Bennekom",
    "FC Bergh",
    "Beuningse Boys",
    "VV Blauw Geel '55",
    "SV Blauw Wit",
    "RKSV Brakkenstein",
    "SV Bredevoort",
    "SC Brummen",
    "SV Buren",
    "BVC '12",
    "BZC '14",
    "VV BZS",
    "CHRC",
    "AVV Columbia",
    "SV Concordia-Wehl",
    "SV Cupa",
    "VV DBV",
    "SV DCS",
    "VV Den Dam",
    "VV DEO",
    "SV DFS",
    "VV Dieren",
    "Dierensche Boys",
    "FC Dinxperlo",
    "DIO '30",
    "SC DIOSA",
    "VV Dodewaard",
    "SC Doesburg",
    "VV Doetinchem",
    "RKSV Driel",
    "D.S.C.",
    "DSV '61",
    "DSZ",
    "DTS Ede",
    "VV DUNO",
    "DVC'26",
    "DVE-Trajanus",
    "DVOL",
    "DVOV",
    "DVS '33",
    "DVSG",
    "DVV Duiven",
    "DZC '68",
    "VV Echteld",
    "VV Ede/Victoria",
    "Edesche Boys",
    "SC EDS",
    "SP Eefde",
    "Eendracht Arnhem",
    "Eerbeekse Boys",
    "EFC '58",
    "EGVV",
    "FC Eibergen",
    "VV Eldenia",
    "Elistha",
    "VV Elspeet",
    "VV Elsweide",
    "EMM Randwijk",
    "VV Emst",
    "SV Epe",
    "SV Epse",
    "VV Erix",
    "ESA Rijkerswoerd",
    "ESC",
    "ESCA",
    "VV Etten",
    "VV Ewijk",
    "Excelsior Zetten",
    "EZC '84",
    "Focus '07",
    "KSV Fortissimo",
    "SV Gelders Eiland",
    "FC Gelre",
    "VV Gendringen",
    "VV Germania",
    "SV De Glind",
    "VV Gorssel",
    "ASV Groen Wit '62",
    "Groesbeekse Boys",
    "SP Groessen",
    "SV Grol",
    "SV Grolse Boys",
    "GSV '38",
    "GSV '63",
    "GVA Doornenburg",
    "GVC",
    "GVV",
    "GVV '63",
    "GWVV",
    "VV Haaften",
    "SP Haarlo",
    "SV Halle",
    "SV 't Harde",
    "SV Harfsen",
    "SV Harskamp",
    "SV Hatert",
    "VV Hattem",
    "SV Hatto Heim",
    "RKVV HAVO",
    "HC '03",
    "VV Hedel",
    "VV Heerde",
    "SV Heerewaarden",
    "Herovina",
    "VV Heukelum",
    "SV Heumen",
    "VV Hierden",
    "SC Hoevelaken",
    "FC Horst",
    "ZVV De Hoven",
    "VV Hulshorst",
    "VV Hurwenen",
    "ISC",
    "VV Jan van Arckel",
    "FC Jeugd '90",
    "Jonge Kracht",
    "SV Juliana '31",
    "SV Keijenburgse Boys",
    "VV Keizerstad",
    "VV Kerkwijk",
    "VV Kesteren",
    "VV De Kieviten",
    "SV Kilder",
    "SC Klarenbeek",
    "VV Klein Dochteren",
    "Kolping-Dynamo",
    "vv Krayenhoff",
    "NSVV FC Kunde",
    "KSH",
    "KSV Vragender",
    "KCVO",
    "SV Leones",
    "FC Lienden",
    "SP Lochem",
    "VV Lochuizen",
    "VV Loenermark",
    "SV Loil",
    "Longa '30",
    "SV Loo",
    "VV Lunteren",
    "VV Mariënveld",
    "MASV",
    "VV M.E.C.",
    "SV MEC '07",
    "SC Meddo",
    "SC Millingen",
    "VV Montferland",
    "MVV '58",
    "SP Neede",
    "NVC",
    "VV Niftrik",
    "SV Nijmegen",
    "Nivo Sparta",
    "SV Noord Veluwe Boys",
    "VV Noordijk",
    "NSC",
    "VV Nunspeet",
    "SV OBW",
    "VV Oeken",
    "VV Oene",
    "ONA '53",
    "VV Ophemert",
    "VV Opijnen",
    "CSV Oranje Blauw",
    "SC Oranje (Arnhem)",
    "SV Orderbos",
    "SV Orion",
    "vv OSC",
    "VV Ostrabeke",
    "SV Otterlo",
    "OVC '85",
    "Overasseltse Boys",
    "OWIOS",
    "SV de Paasberg",
    "Pax Hengelo",
    "RKSV 't Peeske",
    "FC Presikhaaf",
    "SV Prins Bernhard",
    "Quick 1888",
    "SV Ratti",
    "CVV Redichem",
    "SP Rekken",
    "VV Reünie",
    "VV Rheden",
    "RVV Rhelico",
    "VV Rietmolen",
    "SC Rijnland",
    "RKHVV",
    "RKPSC",
    "RKTVC",
    "RKVSC",
    "RKZVC",
    "Robur et Velocitas",
    "RODA '28",
    "Roda Boys Bommelerwaard",
    "VV Rood Wit",
    "Rood-Wit '58",
    "VV Ruurlo",
    "Rossumse Voetbalvereniging",
    "RVW",
    "SCD '33",
    "SCE",
    "SCH",
    "VV Scherpenzeel",
    "VV SCP",
    "VV SCR",
    "SCS",
    "SCZ",
    "SDC Putten",
    "SV SDOO",
    "SDOUC",
    "SDS '55",
    "SDV Barneveld",
    "SDZZ",
    "SEH",
    "VV SHE",
    "SP Silvolde",
    "VV SJN",
    "SKV",
    "SML",
    "SMVC Fair Play",
    "SV Socii",
    "VV Sparta Nijkerk",
    "SV Spero",
    "Sportclub N.E.C.",
    "VV Sprinkhanen",
    "VV Stroe",
    "SVBV",
    "SVDW '75",
    "SVGG",
    "SVHA",
    "SVO '68",
    "SVS '65",
    "SV TEC",
    "VV Teisterbanders",
    "VV Terborg",
    "VV Terschuurse Boys",
    "SV Terwolde",
    "SP Teuge",
    "Theole",
    "VV TKA",
    "De Treffers",
    "Vv Trekvogels",
    "FC Trias",
    "VV Tricht",
    "Sv Twello",
    "VV Uchta",
    "UHC",
    "Ulftse Boys",
    "Uni vv",
    "VV Union",
    "Unitas '28",
    "SV V en L De Vecht",
    "SV Vaassen",
    "SC Valburg",
    "SV de Valleivogels",
    "SC Varsseveld",
    "VDZ",
    "Veensche Boys",
    "VV Veldhoek",
    "SC Veluwezoom",
    "VV De Veluwse Boys",
    "VEVO",
    "Victoria '25",
    "Victoria Boys",
    "Vierhouten '82",
    "VV VIOD",
    "VIOS Beltrum",
    "VIOS Vaassen",
    "VV Voorst",
    "SV Voorwaarts",
    "VV Vorden",
    "VV Vosseveld",
    "CVV Vriendenschaar",
    "VSCO '61",
    "VV Vuren",
    "VVG '25",
    "VVLK",
    "VVO",
    "VVOG",
    "VVOP",
    "SV Waalkanters",
    "VV Wadenoyen",
    "WVV Wageningen",
    "VV Wapenveld",
    "Warnsveldse Boys",
    "WAVV",
    "SV Westendorp",
    "SC Westervoort",
    "WHC",
    "SV Wilp",
    "FC Winterswijk",
    "SV Wissel",
    "VV Witkampers",
    "VV WNC",
    "SV Wodanseck",
    "SC Woezik",
    "VV Wolfersveen",
    "VV Worth-Rheden",
    "WSV",
    "WSV Well",
    "WVW Weurt",
    "WWNA",
    "WZC Wapenveld",
    "VV Zelhem",
    "ZSV Zelos",
    "FC Zutphen",
    "ZVV '56",
    "ZVV De Hoven",
    "Zwart Wit '63",
    "VV Adorp",
    "VV Aduard 2000",
    "VV Alteveer",
    "Amicitia VMC",
    "VV Appingedam",
    "VV ASVB",
    "VV Bareveld",
    "VV Bato",
    "Be Quick 1887",
    "SV Bedum",
    "VV Bellingwolde",
    "SV Blauw Geel '15",
    "VV BNC",
    "VV Borgercompagnie",
    "Corenos",
    "Damacota",
    "DIO Groningen",
    "DIVA '83",
    "SV Drieborg",
    "VV DWZ",
    "VV Eenrum",
    "VV Engelbert",
    "VV Ezinge",
    "VV Farmsum",
    "VV De Fivel",
    "GSAVV Forward",
    "VV Froombosch",
    "FVV",
    "VV GEO",
    "VV Glimmen",
    "VV Godlinze",
    "VV Gorecht",
    "GRC Groningen",
    "VV Grijpskerk",
    "G.V. Groen Geel",
    "VV Groningen",
    "VV Groninger Boys",
    "SC Gronitas",
    "FC Grootegast",
    "VV Gruno",
    "GVAV-Rapiditas",
    "GVB",
    "VV Haren",
    "VV Harkstede",
    "VV Heiligerlee",
    "De Held",
    "VV Helpman",
    "SV de Heracliden",
    "HFC'15",
    "VV Holwierde",
    "VV Hoogezand",
    "HS '88",
    "VV HSC",
    "VV Hunsingo",
    "JVV",
    "Kids United",
    "VV Kiel-Windeweer",
    "VV Kloosterburen",
    "GSVV The Knickerbockers",
    "VV KRC",
    "VV Kwiek",
    "FC LEO",
    "FC Lewenborg",
    "SC Loppersum",
    "Lycurgus",
    "VV Mamio",
    "SV Marum",
    "VV Meeden",
    "VV Meedhuizen",
    "VV Middelstum",
    "MOVV",
    "VV Muntendam",
    "SV Mussel",
    "VV Musselkanaal",
    "NEC Delfzijl",
    "VV Niekerk",
    "VV Nieuweschans",
    "VV Nieuwolda",
    "Noordpool UFC",
    "VV Noordster",
    "VV Noordwolde",
    "OKVC",
    "Oldambtster Boys",
    "VV Omlandia",
    "SV Onderdendam",
    "Onstwedder Boys",
    "VV Oosterhoek",
    "Oosterparkers",
    "VV Opende",
    "Oranje Nassau",
    "VV Pekelder Boys",
    "VV Pelikaan-S",
    "VV De Pelikanen",
    "VV PJC",
    "PKC '83",
    "VV Poolster",
    "VV Potetos",
    "VV Rood Zwart Baflo",
    "SC Scheemda",
    "VV Sellingen",
    "VV SETA",
    "VV SGV",
    "VV Siddeburen",
    "VV SIOS",
    "SJS",
    "VV SPW",
    "SC Stadskanaal",
    "VV Stedum",
    "Sv TEO",
    "FC Ter Apel '96",
    "SV THOS",
    "VV TLC",
    "VV Usquert",
    "VV Veelerveen",
    "VV Veendam 1894",
    "Velocitas 1897",
    "VEV '67",
    "Viboa",
    "VV De Vogels",
    "VVK",
    "VVS Oostwold",
    "VVSV '09",
    "VV Wagenborger Boys",
    "VV Warffum",
    "VV Wedde",
    "VV WEO",
    "VV Westerbroek",
    "VV Westerkwartier",
    "VV Westerlee",
    "VV Westerwolde",
    "VV Wildervank",
    "SV De Wilper Boys",
    "SV Woltersum",
    "WVV 1896",
    "VV 't Zandt",
    "VV ZEC",
    "VV Zevenhuizen",
    "VV ZNC",
    "VV Zuidhorn",
    "SV Abdissenbosch",
    "RKOSV Achates",
    "ADVEO",
    "SV Altweerterheide",
    "AVV America",
    "VV Amstenrade",
    "SV Argo",
    "Astrantia SV",
    "VV Baarlo",
    "RKSV Bekkerveld",
    "Belfeldia",
    "FC Bemelen",
    "VV Berg '28",
    "BEVO",
    "VV Bieslo",
    "SV Blerick",
    "BMR",
    "VV Boekoel",
    "VV Born",
    "Brevendia",
    "SV Brunssum",
    "VV Bunde",
    "BVV '27",
    "VV Caesar",
    "Centrum Boys",
    "VV Chevremont",
    "Conventus '03",
    "RKTVV Crescentia",
    "VV Daalhof",
    "DBSV",
    "DESM",
    "DEV-Arcen",
    "VV DVO",
    "Eendracht '30",
    "SV Egchel",
    "EHC",
    "VV Eijsden",
    "SV Eikenderveld",
    "RKVV Eindse Boys",
    "EMS",
    "SV Epen",
    "RKVV EVV",
    "EWC '46",
    "FCV",
    "Geertruidse Boys",
    "FC Geleen Zuid",
    "Geulsche Boys",
    "Geusselt Sport",
    "GFC '33",
    "VV GKC",
    "SV Grashoek",
    "RKSV Groene Ster",
    "GSV '28",
    "FC Gulpen",
    "GVCG",
    "RKVV Haanrade",
    "RKVV Haelen",
    "SV Haslou",
    "RKVV Havantia",
    "HBC '09",
    "VV HEBES",
    "VV Hellas",
    "VV De Heeg",
    "RKSV Heer",
    "VV Hegelsom",
    "VV Heidebloem",
    "VV Heijen",
    "RKVV Heksenberg",
    "VV Helden",
    "SV Heythuysen",
    "FC Hoensbroek",
    "KSV Horn",
    "HRC '27",
    "SV Hulsberg",
    "IASON",
    "IBC '03",
    "SC Irene",
    "IVO Velden",
    "VV IVS",
    "VV Jabeek",
    "SC Jekerdal",
    "Kakertse Boys",
    "VV Keer",
    "FC Kerkrade-West",
    "VV Kessel",
    "VV Koningslust",
    "SV Kronenberg",
    "KVC Oranje",
    "Kwiek Venlo",
    "SV Laar",
    "SV Langeberg",
    "Laura Hopel Combinatie",
    "VV De Leeuw",
    "SC Leeuwen",
    "RKSV Leonidas-W",
    "SV Leunen",
    "SV Leveroy",
    "VV Limbricht",
    "BSV Limburgia",
    "RKFC Lindenheuvel",
    "VV Linne",
    "SV Lottum",
    "FC Maasgouw",
    "MBC '13",
    "SV Meerssen",
    "RKSV Melderslo",
    "RKSV Merefeldia",
    "SV Merselo",
    "RKSV Meterik",
    "SV Milsbeek",
    "RKSV Minor",
    "MMC Weert",
    "RKVV Montagnards",
    "MVC '19",
    "NEC '92",
    "RKVV Neerbeek",
    "VV Noorbeek",
    "SV Nyswiller",
    "FC ODA",
    "RKSV Olympia Schinveld",
    "SV Oostrum",
    "RKVV Oranje Boys",
    "VV OVCS",
    "SV Panningen",
    "VV Partij",
    "Passart-VKC",
    "PSV '35",
    "VV Puth",
    "RESIA '42",
    "VV Reuver",
    "FC Roerdalen",
    "RFC Roermond",
    "FC RIA",
    "RKVV Rimburg",
    "RIOS '31",
    "RKASV",
    "RKAVC",
    "RKBFC",
    "RKDSO",
    "RKESV",
    "RKHBS",
    "RKHSV",
    "RKHVC",
    "RKIVV",
    "RKMSV",
    "RKMVC",
    "RKSVB",
    "RKSVN",
    "RKSVO",
    "RKSVV",
    "RKTSV",
    "RKUVC",
    "RKVB",
    "RKVCL",
    "RKVVL/Polaris",
    "RKVVM",
    "Rood Groen LVC '01",
    "SV Roggel",
    "VV Roosteren",
    "VV RVU",
    "VV Sanderbout",
    "SCG",
    "VV Schaesberg",
    "VV Scharn",
    "VV Schimmert",
    "SV Schinnen",
    "VV SCM",
    "SHH",
    "SV Sibbe",
    "SV Simpelveld",
    "Sint Joost",
    "VV Sittard",
    "Slekker Boys",
    "SP Slenaken '63",
    "VV SNA",
    "Sparta '18",
    "VV Spaubeek",
    "RKVV Sportclub '25",
    "Sporting Heerlen",
    "Sporting Sittard '13",
    "Sporting ST",
    "RKSV De Ster",
    "VV Stevensweert",
    "Stormvogels '28",
    "Struchter Boys",
    "SC Susteren",
    "Susterse Boys",
    "SVA Bleijerheide",
    "SVC 2000",
    "SVE Einighausen",
    "SVEB",
    "SVH'39",
    "SVM Munstergeleen",
    "SVME",
    "SVN Landgraaf",
    "SVOC '01",
    "SVVH",
    "VV Swalmen",
    "RKSV Sylvia",
    "TSC '04",
    "SV United",
    "UOW02",
    "RKVV Urmondia",
    "RKVV Vaesrade",
    "VCH",
    "Venlosche Boys",
    "SV Venray",
    "VV Veritas",
    "RKVV Vijlen",
    "SV Vilt",
    "Vitesse '08",
    "VV Vlodrop",
    "RKVV Voerendaal",
    "VV VOS",
    "VVV'03",
    "RKVV Walburgia",
    "VV Walram",
    "RKVV WDZ",
    "RKVV Weltania",
    "VV Wijlre",
    "RKVV Wijnandia",
    "Wilhelmina '08",
    "RKVV Willem I",
    "RKSV Wittenhorst",
    "Woander Forest",
    "SV Ysselsteyn",
    "SV Zwart-Wit '19",
    "Achilles Reek",
    "Achilles Veen",
    "VV Acht",
    "VV Achtmaal",
    "SV Advendo",
    "RSC Alliance",
    "VV Almkerk",
    "VV Altena",
    "ASV '33",
    "SV Audacia",
    "Avanti '31",
    "RKSV Avesteyn",
    "VV Baardwijk",
    "VV Baronie",
    "VV Bavel",
    "Bavos",
    "VV Be Ready",
    "VV Beek Vooruit",
    "Beerse Boys",
    "RKVV Bergeijk",
    "FC Bergen",
    "Berghem Sport",
    "VV Berkdijk",
    "VV BES",
    "RKVV Best Vooruit",
    "Bladella",
    "Blauw Geel '38",
    "Blauw Wit '81",
    "SV BLC",
    "BMC",
    "De Bocht '80",
    "BSV Boeimeer",
    "Boekel Sport",
    "RKSV Boerdonk",
    "VV Boskant",
    "RKSV Boxtel",
    "SV Braakhuizen",
    "VV Brabantia",
    "SV Brandevoort",
    "KS Broekhoven",
    "VV Bruheze",
    "RKSV BSC",
    "SV Budel",
    "BVV",
    "BVV '63",
    "SV Capelle",
    "RKVV Casteren",
    "VV Chaam",
    "SV CHC",
    "VV Chrislandia",
    "RKSV Cito",
    "RKSV Cluzona",
    "Constantia",
    "FC Cranendonck",
    "DAW",
    "VV DBS",
    "DEES",
    "RKVV Den Dungen",
    "DESK",
    "RKVV DESO",
    "SV Deurne",
    "DEVO",
    "VV DHV",
    "RKVV DIA",
    "Dijkse Boys",
    "VV Dinteloord",
    "DIOZ",
    "RKSV DIVO",
    "RKVV Dommelen",
    "VV Dongen",
    "SV DOSKO",
    "DOSKO '32",
    "DOSL",
    "FC Drunen",
    "VV DSE",
    "DSV",
    "Dussense Boys",
    "DVG",
    "DVO '60",
    "VV DVS",
    "DVVC",
    "SV DWSH '18",
    "EDN '56",
    "EFC",
    "FC Eindhoven AV",
    "ELI",
    "VV Elsendorp",
    "SC Elshout",
    "RKVV EMK",
    "Emplina",
    "FC Engelen",
    "RKVV Erp",
    "Essche Boys",
    "SV Estria",
    "EVVC",
    "VV Excellent",
    "VV De Fendert",
    "Festilent",
    "RKVV Fiducia",
    "VV Gassel",
    "SC Gastel",
    "GDC",
    "VV Geldrop",
    "VV Gemert",
    "RKVV GESTA",
    "VV Gestel",
    "VV Giessen",
    "VV Gilze",
    "Gloria-UC",
    "VV Good Luck",
    "RKVV Grenswachters",
    "RKSV Groen Wit",
    "GSBW",
    "TSV Gudok",
    "The Gunners",
    "GVV '57",
    "VV Haarsteeg",
    "RKSV Halsteren",
    "VV Handel",
    "VV Hapert",
    "Hapse Boys",
    "HBV",
    "VV Heeswijk",
    "RKSV Heeze",
    "SV Helenaveen Griendtsveen",
    "SC Helmondia",
    "VV Helvoirt",
    "Herpinia",
    "HHC '09",
    "S.V. Hilvaria",
    "HMVV",
    "VV Hoeven",
    "SC Hoge Vucht",
    "VV Holthees-Smakt",
    "VV Hoogeloon",
    "HSC '28",
    "HSE",
    "VV Hulsel",
    "HVCH",
    "HVV Helmond",
    "HZ '75",
    "VV Internos",
    "VV Irene",
    "Irene '58",
    "RKVV JEKA",
    "Jong Brabant",
    "Juliana Mill",
    "JVC Cuijk",
    "RKVV Keldonk",
    "VV Klundert",
    "Knegselse Boys",
    "VV Kogelvangers",
    "Kozakken Boys",
    "SC Kruisland",
    "Lepelstraatse Boys",
    "SV LEW",
    "SV Lierop",
    "RKSV Liessel",
    "TSV Longa",
    "LSV Boxtel",
    "VV Maarheeze",
    "Maaskantse Boys",
    "VV Macharen",
    "Madese Boys",
    "RKVV Maliskamp",
    "RKSV Margriet",
    "VV Mariahout",
    "Marjola Girls",
    "SV Marvilde",
    "RKVV Menos",
    "TSVV Merlijn",
    "RKVV METO",
    "RKSV Mierlo-Hout",
    "Mifano",
    "Milheezer Boys",
    "MOC '17",
    "Moerse Boys",
    "FC Moerstraten",
    "VV Molenschot",
    "RKSV MULO",
    "VV MVC",
    "RKVV Nederwetten",
    "VV Neerkandia",
    "Neerlandia '31",
    "RKSV Nemelaer",
    "NEO '25",
    "VV Netersel",
    "RKVV Nieuw Borgvliet",
    "Nieuw Woensel",
    "VV Nieuwkuijk",
    "VV Nijnsel",
    "NLC '03",
    "NOAD",
    "NOAD '32",
    "VV Nooit Gedacht",
    "VV Noordhoek",
    "SV Nordea",
    "VV NSV",
    "RKSV Nuenen",
    "Nulandia",
    "NVS",
    "NWC",
    "ODC",
    "RKSV Odiliapeel",
    "RKVV ODIO",
    "VV Oirschot Vooruit",
    "OJC Rosmalen",
    "OKSV",
    "VV Ollandia",
    "Olympia '18",
    "Olympia '60",
    "Olympia Boys",
    "SC Olympus",
    "SV ONDO",
    "VV ONI",
    "Ons Vios",
    "VV Oosterhout",
    "SC Oranje Zwart Helmond",
    "OSC'45",
    "SV OSS '20",
    "VV Oudemolen",
    "SV OVC '63",
    "OVV '67",
    "VV PCP",
    "RKSV Prinses Irene",
    "ESVV Pusphaira",
    "VV Raamsdonk",
    "Racing Boys",
    "FC de Rakt",
    "VV De Raven",
    "VV Ravenstein",
    "SV Real Lunet",
    "SV Reeshof",
    "Reusel Sport",
    "RKSV Rhode",
    "VV Riel",
    "VV Riethoven",
    "FC Right-Oh",
    "VV Rijen",
    "Rijswijkse Boys",
    "RKVV Rimboe",
    "RKDSV",
    "RKDVC",
    "RKGSV",
    "RKJVV",
    "RKKSV",
    "RKPVV",
    "RKTVV",
    "RKVVO",
    "Rood-Wit '62",
    "Rood-Wit '67",
    "SV Rood-Wit Veldhoven",
    "RKSV Rood-Wit Willebrord",
    "RKVV Roosendaal",
    "RPC",
    "VV RSV",
    "CVV Rust Roest",
    "SV Ruwaard",
    "VV RWB",
    "SAB",
    "VV Sambeek",
    "RKSV Sarto",
    "VV SBC",
    "SBV",
    "FC Schadewijk",
    "RKVV Schijf",
    "RKSV Schijndel",
    "De Schutters",
    "SCI",
    "SCMH",
    "VV SCO",
    "SCV '58",
    "SDDL",
    "SDO '39",
    "SEOLTO",
    "SES",
    "RKVV Sint-Michielsgestel",
    "VV SIOL",
    "SJVV",
    "VV Sleeuwijk",
    "SV Someren",
    "Sparta '25",
    "Sparta '30",
    "Spoordonkse Boys",
    "SV Sprundel",
    "SPV",
    "SSC '55",
    "SSE",
    "SSS'18",
    "VV Steenbergen",
    "VV Steensel",
    "RKSV Sterksel",
    "Stiphout Vooruit",
    "VV SVC",
    "VV SVG",
    "SVS Stevensbeek",
    "SVSH",
    "SVSOS",
    "SvSSS",
    "SV Terheijden",
    "VV Terlo",
    "TGG",
    "SV Tivoli",
    "RKVV Tongelre",
    "SV TOP",
    "VV Toxandria",
    "TPO",
    "Trinitas Oisterwijk",
    "VV TSC",
    "Tuldania",
    "TVC Breda",
    "FC Uden",
    "UDI '19",
    "SV Ulicoten",
    "RKSV Ulysses",
    "VV UNA",
    "Unitas '30",
    "Unitas '59",
    "VV Uno Animo",
    "UVV '40",
    "RKVV Val Aan",
    "VV De Valk",
    "SV Valkenswaard",
    "VCA",
    "VCB",
    "VV VCO",
    "VCW",
    "Veerse Boys",
    "RKSV Venhorst",
    "VV Vessem",
    "Vianen Vooruit",
    "VV Victoria '03",
    "VV Viola",
    "VIOS '38",
    "VV Virtus",
    "VV VIVOO",
    "Vlijmense Boys",
    "VOAB",
    "RKVV Volharding",
    "RKSV Volkel",
    "Vorstenbossche Boys",
    "VOW",
    "VV Vrederust",
    "VVC '68",
    "VVR",
    "RKVV Waalre",
    "VV Waspik",
    "WDS '19",
    "WEC",
    "RKSV De Weebosch",
    "SC Welberg",
    "RKSV Were Di",
    "VV Wernhout",
    "Westerbeekse Boys",
    "The White Boys",
    "WHV",
    "RKVV Wilhelmina",
    "Wilhelmina '26",
    "Wilhelmina Boys",
    "VV WODAN",
    "Woenselse Boys",
    "VV Woudrichem",
    "WSC",
    "RKTSV WSJ",
    "WVV '67",
    "SC 't Zand",
    "VV ZIGO",
    "ZSC",
    "ZSV",
    "VV Zundert",
    "Vv De Zwaluw",
    "Zwaluw VFC",
    "VV Zwaluwe",
    "VV Aalsmeer",
    "AGSV Aartswoud",
    "SV Abbenes",
    "ADO '20",
    "AFC",
    "AFC '34",
    "AFC TABA",
    "AGB",
    "SC AH '78",
    "Ajax Zaterdag",
    "VV ALC",
    "Alcmaria Victrix",
    "VV Alkmaarsche Boys",
    "BSV Allen Weerbaar",
    "SV Alliance '22",
    "VV Altius",
    "SV Always Forward",
    "vv Amstelveen",
    "FC Amsterdam",
    "FC Amsterdamse Bos",
    "FC Aalsmeer",
    "Amsterdam Seref Spor",
    "AMVJ",
    "AVV Andijk",
    "Apollo '68",
    "SV Asonia",
    "VV Assendelft",
    "ASV '55",
    "ASV '65",
    "SC Badhoevedorp",
    "SV Beemster",
    "Berdos",
    "BSV Bergen",
    "VV Berkhout",
    "VV De Beursbengels",
    "SV Beverwijk",
    "BFC",
    "BKC",
    "CVV Blauw Wit (W)",
    "FC Blauw-Wit Amsterdam",
    "BVC Bloemendaal",
    "VV De Blokkers",
    "CSV BOL",
    "De Brug",
    "SV BSM",
    "SC Buitenveldert",
    "BVV '31",
    "BZC '13",
    "VV Callantsoog",
    "FC Castricum",
    "FC Chabab",
    "Con Zelo",
    "CTO '70",
    "RKSV DCG",
    "RKVV DEM",
    "FC Den Helder",
    "SV DESS",
    "DEVO '58",
    "SV Diemen",
    "ASV De Dijk",
    "Dindua",
    "SV DIO",
    "SV DIOS",
    "VV Dirkshorn",
    "DRC",
    "HVV DSK",
    "DSOV",
    "RKVV DSS",
    "SV DTS",
    "Duinrand S",
    "DVC Buiksloot",
    "DVVA",
    "VV DWB",
    "VV DWOW",
    "AFC DWS",
    "SC Dynamo",
    "DZS",
    "HFC EDO",
    "SC Eendracht '82",
    "VV Egmondia",
    "EVC",
    "AVV FIT",
    "ASV De Flamingo's '64",
    "VV Flevo",
    "SV De Foresters",
    "ASV Fortius",
    "Fortuna Wormerveer",
    "SV Geel Wit '20",
    "SV Geel-Zwart '30",
    "SV Geinburgia",
    "ASV Germaan/De Eland",
    "GeuzenMiddenmeer",
    "SC 't Gooi",
    "SV Graftdijk",
    "VV Grasshoppers",
    "SV 's-Graveland",
    "Haarlem-Kennemerland",
    "Hauwert '65",
    "RKSV HBC",
    "VV HBOK",
    "HCSC",
    "HFC Heemstede",
    "SC Hercules Zaandam",
    "FC Hilversum",
    "HVV Hollandia",
    "VV Hollandia T",
    "SV Hoofddorp",
    "HOSV",
    "VV HSV",
    "HSV Sport 1889",
    "Hugo Boys",
    "SV Huizen",
    "VV IJmuiden",
    "IJ.V.V. Stormvogels",
    "SV Ilpendam",
    "IVV",
    "VV Jisp",
    "CVV Jong Hercules",
    "CSV Jong Holland",
    "JOS Watergraafsmeer",
    "JVC Julianadorp",
    "VV Kaagvogels",
    "SV Kadoelen",
    "VV Kagia",
    "SV KDO",
    "BVV De Kennemers",
    "KFC",
    "VV KGB",
    "SV KLM",
    "VV Knollendam",
    "SV Koedijk",
    "VV Kolping Boys",
    "Koninklijke HFC",
    "SV De Koog",
    "KSV",
    "VV Kwadijk",
    "Kwiek '78",
    "SV Laren '99",
    "Legmeervogels",
    "VV Limmen",
    "SV Loosdrecht",
    "LSVV",
    "SV Marken",
    "FC Medemblik",
    "SV De Meer",
    "Meervogels '31",
    "SV De Meteoor",
    "VV MOC",
    "VV Monnickendam",
    "SC Muiden",
    "SC Muiderberg",
    "AFC Nautilus",
    "VV Nederhorst",
    "NFC/Brommer",
    "SV Nieuw Sloten",
    "VV Nieuwe Niedorp",
    "NVC",
    "ODIN '59",
    "OFC",
    "SV Olympia '25",
    "Olympia Haarlem",
    "RKVV Onze Gezellen",
    "SV Oosterend",
    "VV Oosthuizen",
    "VV Opperdoes",
    "OSC Amsterdam",
    "OSO",
    "OSV",
    "SV Ouderkerk",
    "VV Oudesluis",
    "SC Overamstel",
    "SV Overbos",
    "RKSV Pancratius",
    "SV Parkstad",
    "SV Petten",
    "FC Portugal Amsterdam",
    "VV PSZ",
    "FC Purmerend",
    "SC Purmerland",
    "VPV Purmersteijn",
    "SV Rap",
    "RCH",
    "VV RCZ",
    "SV Real Sranang",
    "VV Reiger Boys",
    "SV De Rijp",
    "RKAV",
    "RKAVIC",
    "RKDES",
    "RKEDO SV",
    "RKSV RODA '23",
    "Rood-Wit Zaanstad",
    "RKVV Saenden",
    "Schagen United",
    "VV Schellinkhout",
    "VV Schoten",
    "SCW",
    "SDO Bussum",
    "SDOB",
    "ASC SDW",
    "AVV SDZ",
    "VV SEW",
    "Sint Boys DES",
    "RKSV Sint George",
    "AVV Sloterdijk",
    "SV Spaarnwoude",
    "VV Spartanen",
    "SC Spirit '30",
    "Sporting Amsterdam",
    "Sporting Krommenie",
    "Sporting Martinus",
    "Sporting Noord",
    "SV Sporting S",
    "SSV",
    "VV Strandvogels",
    "VV Succes",
    "SVA Assendelft",
    "SVAP '74",
    "VV SVIJ",
    "SVOW",
    "SVW '27",
    "AVV Swift",
    "SV Terrasvogels",
    "VV Texel '94",
    "VV THB",
    "RKSV TOB",
    "AVV TOG",
    "TOS-Actief",
    "TSV Twisk",
    "FC Uitgeest",
    "SV United/DAVO",
    "VV UNO",
    "FC VVC",
    "SV De Valken",
    "RKVV Velsen",
    "FC Velsenoord",
    "VV Vesdo",
    "VEW",
    "HC & FC Victoria",
    "Victoria O",
    "VIOS-W",
    "Vitesse '22",
    "CVV Vlug en Vaardig",
    "SV Koedijk",
    "SV Vogelenzang",
    "RKAV Volendam",
    "SC Voorland",
    "SV Vrone",
    "VSV",
    "VVA/Spartaan",
    "FC VVC",
    "VVGA",
    "VVH/Velserbroek",
    "VVS '46",
    "VV VVW",
    "VV VZV",
    "ASV Wartburgia",
    "HSV Wasmeer",
    "VV Waterloo",
    "SV Watervogels",
    "WBSV",
    "FC Weesp",
    "VV West Frisia",
    "SV Westfriezen",
    "VVV Westzaan",
    "VV De Wherevogels",
    "CV Wieringermeer",
    "VV Wieringerwaard",
    "SV Wijk aan Zee",
    "VV Winkel",
    "VV Wiron",
    "SV WMC",
    "VV Woudia",
    "WSV '30",
    "WSW",
    "WV-HEDW",
    "FC Zaandam",
    "ZVV Zaandijk",
    "ZVV Zaanlandia",
    "SV Zandvoort",
    "Z.A.P.",
    "ZCFC",
    "SV ZDH",
    "AVV Zeeburgia",
    "MSV Zeemacht",
    "VV Zeevogels",
    "ZOB",
    "VV De Zouaven",
    "VV ZRC Herenmarkt",
    "ZSGOWMS",
    "SV Zuidermeer",
    "Zuidoost United",
    "HSV De Zuidvogels",
    "RKVV Zwaagdijk",
    "Zwaluwen '30",
    "VV Zwanenburg",
    "ABS Bathmen",
    "Achilles '12",
    "Cvv Achilles",
    "AJc '96",
    "SV Almelo",
    "FC Aramea",
    "ASC '62",
    "ASV '57",
    "vv ATC '65",
    "Avanti Wilskracht",
    "VV Avereest",
    "SC Balkbrug",
    "Barbaros",
    "Be Quick '28",
    "VV Bentelo",
    "VV Bergentheim",
    "FC Berghuizen",
    "VV Berkum",
    "VV Blankenham",
    "ZVV Blauw Wit '66",
    "BZSV de Blauwwitters",
    "SV Blokzijl",
    "SV Bon Boys",
    "BVV Borne",
    "RKSV Bornerbroek",
    "SV Broekland",
    "VV Bruchterveld",
    "BSC Unisson",
    "VV Buurse",
    "KSV BWO",
    "FC het Centrum",
    "SV Colmschate '33",
    "CSV '28",
    "Sportclub Daarle",
    "VV Daarlerveen",
    "SV Dalfsen",
    "DVV Davo",
    "SV Dedemsvaart",
    "SV Delden",
    "VV Den Ham",
    "VV DES",
    "DESZ",
    "DETO Twenterand",
    "Sportclub Deventer",
    "VV Diepenheim",
    "Dieze West",
    "DKB",
    "DOS '37",
    "DOS Kampen",
    "DRC '12",
    "VV Drienerlo",
    "DSC Diepenveen",
    "DSVD",
    "DTC '07",
    "EDON",
    "GVV Eilermark",
    "v.v. EMMS",
    "EMOS",
    "ENC '09",
    "Sportclub Enschede",
    "Enschedese Boys",
    "SV Enter",
    "Enter Vooruit",
    "ZVV De Esch",
    "Excelsior '31",
    "VC Fleringen",
    "VV De Gazelle",
    "SC Genemuiden",
    "GFC",
    "SV Giethoorn SE",
    "VV Glanerbrug",
    "DVV Go-Ahead",
    "Go-Ahead Kampen",
    "SV Gramsbergen",
    "VV Haaksbergen",
    "SV Haarle",
    "VV Hardenberg '85",
    "SV Hector",
    "VV Hellendoorn",
    "VV 's-Heerenbroek",
    "SV Heeten",
    "VV Heino",
    "SV Helios",
    "HVV Hengelo",
    "AVC Heracles",
    "HHC Hardenberg",
    "VV Hoeve Vooruit",
    "VV Holten",
    "VV Hoonhorst",
    "HSC '21",
    "HTC",
    "Hulzense Boys",
    "VV IJhorst",
    "DVV IJsselstreek",
    "IJVV",
    "SV Juliana '32",
    "Juventa '12",
    "JVC Dedemsvaart",
    "VV Kampen",
    "VV KHC",
    "VV Kloosterhaar",
    "Koninklijke UD",
    "KOSC",
    "VV Kuinre",
    "VV Langeveen",
    "SC Lemele",
    "VV Lemelerveld",
    "VV Lettele",
    "KVV Losser",
    "LSV Lonneker",
    "AVC Luctor et Emergo",
    "SV De Lutte",
    "SC Lutten",
    "VV Manderveen",
    "VV Mariënberg",
    "SV Mariënheem",
    "SC Markelo",
    "MVV '29",
    "MVV '69",
    "RKSV NEO",
    "SV Nieuw Heeten",
    "S.V. Nieuwleusen",
    "Olde Veste '54",
    "FC Oldemarkt",
    "VV Oldenzaal",
    "VV Olympia '28",
    "Oranje Nassau",
    "VV Oranje Zwart",
    "OVC '21",
    "Sportclub Overdinkel",
    "SC Overwetering",
    "OZC",
    "PH Almelo",
    "EVV Phenix",
    "AVC La Première",
    "EFC PW 1885",
    "Quick '20",
    "SV Raalte",
    "FC RDC",
    "VV Reutum",
    "Vv Rigtersbleek",
    "SC Rijssen",
    "SV Rijssen",
    "Rohda Raalte",
    "VV Rood Zwart",
    "SC Rouveen",
    "VV RSC",
    "Saasveldia",
    "DVV Sallandia",
    "SCD '83",
    "SV Schalkhaar",
    "VV Scheerwolde",
    "SDC '12",
    "SV SDOL",
    "cvv Sparta Enschede",
    "Sportlust Glanerbrug",
    "Sportlust Vroomshoop",
    "VV Staphorst",
    "VV Steenwijk",
    "VV Steenwijker Boys",
    "SV Steenwijkerwold",
    "RKVV STEVO",
    "HFC Storica",
    "FC Suryoye/Mediterraneo",
    "SVBS '77",
    "VV SVI",
    "SVV '56",
    "SVV '91",
    "SVVN",
    "SVZW Wierden",
    "De Tubanters 1897",
    "HVV Tubantia",
    "RKSV De Tukkers",
    "DVV Turkse Kracht",
    "TVC '28",
    "TVO",
    "TVV",
    "vv Twenthe",
    "VV UD Weerselo",
    "UDI Enschede",
    "FC Ulu Spor",
    "USV Nieuwleusen",
    "SV Vasse",
    "SV VENO",
    "VHK",
    "Vv Victoria '28",
    "VV Vilsteren",
    "RKSV VOGIDO",
    "VV Voorwaarts (Westerhaar)",
    "VOSTA",
    "Vroomshoopse Boys",
    "VSW",
    "SV Welsum",
    "SC Wesepe",
    "Wijhe '92",
    "VV Wijthmen",
    "SV Wilhelminaschool",
    "VV Willemsoord",
    "VV Wilsum",
    "WVF",
    "WVV '34",
    "VV WWV",
    "ZAC",
    "SV Zalk",
    "Zenderen Vooruit",
    "VV Zuid Eschmarke",
    "RKSV De Zweef",
    "SV Zwolle",
    "Zwolsche Boys",
    "FC Abcoude",
    "SV Achterveld",
    "VV Amsvorde",
    "VV APWC",
    "VVU Ardahanspor",
    "SV Argon",
    "SV Aurora",
    "SV Austerlitz",
    "SV Baarn",
    "VV Benschop",
    "FC De Bilt",
    "VV Brederodes",
    "FC Breukelen",
    "VV Bunnik '73",
    "VV Cabauw",
    "SV Candia '66",
    "SV CDW",
    "CJVV",
    "VV Cobu Boys",
    "CSW",
    "FC Delta Sports'95",
    "DESTO",
    "DEV",
    "DHSC",
    "DOB",
    "Domstad Majella",
    "DOSC",
    "VV DOVO",
    "VV De Dreef",
    "FC Driebergen",
    "DSO/Ultrajectum",
    "DVSA",
    "DVSU",
    "DWSM",
    "DWSV",
    "UCS EDO",
    "VV Eemboys",
    "VV Eemdijk",
    "SV Eemnes",
    "USV Elinkwijk",
    "Eminent Boys",
    "SC Everstein",
    "Faja Lobi KDS",
    "VV FZO",
    "SV Geinoord",
    "VV 't Goy",
    "GVVV",
    "VV HDS",
    "VV Hees",
    "USV Hercules",
    "SV Hertha",
    "SV HMS",
    "VV Hoogland",
    "VV Hooglanderveen",
    "VV Hoograven",
    "SV Houten",
    "HSV '69",
    "HVC",
    "IJsselmeervogels",
    "IJFC",
    "VV Jonathan",
    "JSV Nieuwegein",
    "VV Kamerik",
    "SV Kampong",
    "VV Kismet",
    "VV Kockengen",
    "KVVA",
    "VV Linschoten",
    "SV Lopik",
    "VV Maarssen",
    "Magreb '90",
    "VV De Meern",
    "VV De Merino's",
    "MSV '19",
    "VV Musketiers",
    "ASC Nieuwland",
    "SV Nieuw Utrecht",
    "OSV NITA",
    "SV Odijk",
    "VV Odin",
    "Odysseus '91",
    "VV Oranje Wit (Elst)",
    "OSM '75",
    "OVS Oudewater",
    "ZSC Patria",
    "VV De Posthoorn",
    "ksv PVC",
    "PVCV Vleuten",
    "AFC Quick 1890",
    "VV Renswoude",
    "SV Rivierwijkers",
    "RODA '46",
    "VV RUC",
    "SV Saestum",
    "SCH '44",
    "VV Schalkwijk",
    "SEC",
    "SV SIVEO '60",
    "SO Soest",
    "SV Spakenburg",
    "Sporting '70",
    "Sportlust '46",
    "SPV '81",
    "VV Sterrenwijk",
    "SVF Cothen",
    "SVL",
    "SVM Maartensdijk",
    "SVMM",
    "SVP",
    "TOV",
    "VV UNIO",
    "SV Unitas '48",
    "asv UVV",
    "SV De Vecht",
    "VV Veenendaal",
    "VEP",
    "VV Vianen",
    "VIOD",
    "VV 't Vliegdorp",
    "VV Voorwaarts (Utrecht)",
    "VV VOP",
    "VV VRC",
    "VSV Vreeswijk",
    "VSC",
    "VVA Achterberg",
    "VVIJ",
    "VVJ",
    "VVOO",
    "VVZ '49",
    "VVZA",
    "SC Woerden",
    "VV Woudenberg",
    "SV Zeist",
    "Zwaluwen Utrecht 1911",
    "AVC Aardenburg",
    "SV Apollo '69",
    "VV Arnemuiden",
    "FC Axel",
    "VV Bevelanders",
    "VV Biervliet",
    "VV Borssele",
    "VV Breskens",
    "ASV Brouwershaven",
    "Bruse Boys",
    "VV Cadzand",
    "VV Clinge",
    "VV Colijnsplaatse Boys",
    "Corn Boys",
    "Cortgene",
    "FC Dauwendaele",
    "DFS",
    "VV Domburg",
    "SV Duiveland",
    "DZC '09",
    "VV GOES",
    "GPC Vlissingen",
    "VV Graauw",
    "VV Groede",
    "Hansweertse Boys",
    "VV 's-Heer Arendskerke",
    "SV Heinkenszand",
    "SV Hoedekenskerke",
    "HSV Hoek",
    "VV Hontenisse",
    "VV Hoofdplaat",
    "VV Hulsterloo",
    "HVV '24",
    "VV IJzendijke",
    "Jong Ambon",
    "VV Kapelle",
    "VV Kloetinge",
    "RKVV Koewacht",
    "VV Krabbendijke",
    "VV Kruiningen",
    "VV Kwadendamme",
    "VV Lewedorpse Boys",
    "VV Luctor '88",
    "VV de Meeuwen",
    "SV MZC '11",
    "MZVC",
    "SV Nieuwdorp",
    "VV Nieuwland",
    "VV NOAD '67",
    "VV de Noormannen",
    "SV Oostburg",
    "VV Oostkapelle",
    "SV Ouwerkerk",
    "VV De Patrijzen",
    "VV Philippine",
    "VV RCS",
    "SV Renesse",
    "RIA-W",
    "VV Rillandia",
    "SV Robur",
    "VV Schoondijke",
    "SDO '63",
    "VV Serooskerke",
    "SKNWK",
    "SV Sluis",
    "VV Sluiskil",
    "SV Smerdiek",
    "SPS",
    "VV Spui",
    "SSV '65",
    "SC Stavenisse",
    "VV STEEN",
    "SVD",
    "VV Terhole",
    "VV Terneuzen",
    "VV Terneuzense Boys",
    "Tholense Boys",
    "VCK",
    "VV Veere",
    "VC Vlissingen",
    "VV Vogelwaarde",
    "VV Volharding '32",
    "VV Vosmeer",
    "SC Waarde",
    "SV Walcheren",
    "VV Wemeldinge",
    "WHS",
    "WIK '57",
    "VV Wolfaartsdijk",
    "VV Yerseke",
    "VV Zaamslag",
    "Zeeland Sport",
    "Zeelandia Middelburg",
    "ZSC '62",
    "SV Aarlanderveen",
    "VV Abbenbroek",
    "ABF",
    "ADS Den Haag",
    "RKSV Aeolus",
    "RVV AGE-GGK",
    "VV De Alblas",
    "VV Alblasserdam",
    "VV Alexandria '66",
    "SV Alkmania",
    "AVV Alphen",
    "VV Alphense Boys",
    "VV Alphia",
    "RKSV Altior",
    "VV Ameide",
    "Ammerstolse SV",
    "SC Amstelwijck",
    "R.S.V. Antibarbari",
    "SV ARC",
    "VV Ariston '80",
    "ASV Arkel",
    "ASW",
    "ASC",
    "VV ASWH",
    "BVV Barendrecht",
    "CVV Be Fair",
    "VV Bergambacht",
    "CVV Berkel",
    "SV Bernardus",
    "MSV De Betrokken Spartaan",
    "FC Binnenmaas",
    "FC Blankenburg",
    "RKSV Blauw-Zwart",
    "RVV Blijdorp",
    "VV BMT",
    "VV Bodegraven",
    "SV Bolnes",
    "FC Boshuizen",
    "SC Botlek",
    "VV Brielle",
    "BSC '68",
    "SV BVCB",
    "BZC/Zuiderpark",
    "vv Capelle",
    "HSV Celeritas",
    "SV Charlois",
    "CION",
    "VV CKC",
    "RVV COAL",
    "Concordia (Delft)",
    "SV Concordia",
    "SV CWO",
    "DBGC",
    "VV DCV",
    "Delfia",
    "DVV Delft",
    "SV Deltasport",
    "VV Den Bommel",
    "SV Den Hoorn",
    "DFC",
    "DVV DHC",
    "SV DHL",
    "RVV DHZ",
    "SV Die Haghe",
    "VV Dilettant",
    "RKSV DoCoS",
    "SV DONK",
    "FC Dordrecht Amateurs",
    "RKSV DOSR",
    "Vv Drechtstreek",
    "DRL",
    "SV DSO",
    "VV DSVP",
    "VV Dubbeldam",
    "Duindorp SV",
    "HSV DUNO",
    "DVC Delft",
    "DVO '32",
    "DVV '09",
    "SV DWO",
    "VV EBOH",
    "De Egelantier Boys",
    "SC Emma",
    "SV Erasmus",
    "HSV Escamp",
    "VV ESTO",
    "Excelsior '20",
    "VV Excelsior Maassluis",
    "SC Feyenoord",
    "RKVV FIOS",
    "MSV en AV Flakkee",
    "BGC Floreant",
    "Football Factory",
    "VV Foreholte",
    "Forum Sport",
    "DSV Full Speed",
    "RKSV GDA",
    "GHC",
    "GHVV'13",
    "GJS",
    "GLZ Delfshaven",
    "GOL Sport",
    "SC Gorkum",
    "SV Gouda",
    "VV Gouderak",
    "Goudswaardse Boys",
    "VV GOZ",
    "Graaf Willem II VAC",
    "FC 's-Gravenzande",
    "VV 's-Gravendeel",
    "VV Groeneweg",
    "VV Groot Ammers",
    "VV Groote Lindt",
    "GSC/ODS",
    "GSC ESDO",
    "GSV",
    "VV GWS",
    "VV Haagse Hout",
    "VV Haastrecht",
    "VV Hardinxveld",
    "Hargasport",
    "Hazerswoudse Boys",
    "HBS-Craeyenhout",
    "HBSS",
    "VV HDV",
    "VV Heerjansdam",
    "SV Heinenoord",
    "VV Hekelingen",
    "VV Hellevoetsluis",
    "HVV Hercules",
    "VV Herkingen '55",
    "PSV Hermandad",
    "Hermes DVS",
    "VV Hillegom",
    "VV Hillegersberg",
    "VV HMC",
    "HMSH",
    "RSV Hoekpolder",
    "SV Honselersdijk",
    "SV Houtwijk",
    "HOV/DJSCR",
    "HPSV",
    "HSSC '61",
    "HVC '10",
    "Kon. HVV",
    "VV HVZ",
    "VV HWD",
    "IFC",
    "CVV De Jodan Boys",
    "VV De Jonge Spartaan",
    "V.v. Katwijk",
    "VV Kethel Spaland",
    "SV Kickers '69",
    "SV KMD",
    "RVV Kocatepe",
    "VV Koudekerk",
    "VV KSD-Marine",
    "HVV Laakkwartier",
    "Leerdam Sport '55",
    "VV Leidsche Boys",
    "VV Lekkerkerk",
    "SV Leidschenveen",
    "VV Lekvogels",
    "RKSV Leonidas",
    "FC Lisse",
    "RVV LMO",
    "SV Lombardijen",
    "SV Loosduinen",
    "VV LRC",
    "LSVV '70",
    "LVV Lugdunum",
    "VV Lyra",
    "VV Maasdijk",
    "SC Maasstad Tediro",
    "FC Maense",
    "RKVV Meerburg",
    "SV Meerkerk",
    "VV Meeuwenplaat",
    "VV Melissant",
    "MMO",
    "VV Moerkapelle",
    "SC Monster",
    "VV Moordrecht",
    "FC Mozaïek",
    "MSV '71",
    "MVV '27",
    "VV Naaldwijk",
    "NBSVV",
    "Neptunus-Schiebroek",
    "SV Nicolaas Boys",
    "VV Nieuw-Lekkerland",
    "VV Nieuwenhoorn",
    "VV Nieuwerkerk",
    "SV Nieuwkoop",
    "VV Van Nispen",
    "NOCKralingen",
    "SV Noordeloos",
    "Vv Noordwijk",
    "SV Nootdorp",
    "NSV '46",
    "NSVV",
    "NTVV",
    "HVV ODB",
    "FC Oegstgeest",
    "VV OFB",
    "OHVV",
    "OLIVEO",
    "GC & FC Olympia",
    "SV Ommoord",
    "Vv ONA",
    "SV Oosterheem",
    "SV Oranje Wit",
    "Oranjeplein-Postduiven",
    "OSV Oud-Beijerland",
    "VV Oude Maas",
    "Overmaas Rotterdam",
    "OVV",
    "VV Papendrecht",
    "ZVV Pelikaan",
    "FC Perkouw",
    "Vv Pernis",
    "VV Peursum",
    "PFC",
    "PGS/VOGEL",
    "SV Piershil",
    "PKC '85",
    "PSV Poortugaal",
    "PPSC",
    "FC Pretoria R.",
    "H.V. & C.V. Quick",
    "KVV Quick Boys",
    "Quick Steps",
    "VV Quintus",
    "GVV Raptim",
    "Hvv RAS",
    "RKSV RCD",
    "RCL",
    "SV RDM",
    "Real Zoetermeer",
    "CVC Reeuwijk",
    "SC REMO",
    "RFC 2000",
    "VV Rhoon",
    "VV Rijnmond Hoogvliet Sport",
    "Rijnsburgse Boys",
    "VV de Rijnstreek",
    "FC Rijnvogels",
    "VV Rijsoord",
    "RKAVV",
    "RKDEO",
    "SV ROAC",
    "VV Rockanje",
    "Rohda '76",
    "LV Roodenburg",
    "SV Rotterdam United",
    "VV Rozenburg",
    "RVC '33",
    "RVVH",
    "VV Schelluinen",
    "SVV Scheveningen",
    "VV Schipluiden",
    "VV Schoonhoven",
    "SCO '63",
    "SDV Rotterdam",
    "RVV Semper Altius",
    "SEP",
    "SEV",
    "Vv SHO",
    "SV Simonshaven",
    "VV SIZO",
    "VV SJC",
    "VV SJZ",
    "VV Sliedrecht",
    "SV Slikkerveer",
    "VV Smitshoek",
    "VV SNS",
    "SV Soccer Boys",
    "Spartaan '20",
    "VV Spijkenisse",
    "VV Spirit",
    "VV Sportief",
    "Sporting Leiden",
    "SSS",
    "SSW",
    "VV SteDoCo",
    "RV & AV Steeds Hooger",
    "VV Stellendam",
    "De Ster",
    "VV Stolwijk",
    "Stompwijk '92",
    "V.V. Streefkerk",
    "VV Strijen",
    "SV Besiktas",
    "SVC '08",
    "VV SVH",
    "SVS Capelle",
    "SVV",
    "SVW",
    "RVV Swift Boys",
    "TAC '90",
    "SVVV Taurus",
    "TAVV",
    "VV Ter Leede",
    "RKVV Teylingen",
    "TOGB",
    "SSV Toofan",
    "TransvaliaZW",
    "GVV Unitas",
    "VV UVS",
    "Valken '68",
    "VCS",
    "MVV VDL",
    "SV VELO",
    "VV Verburch",
    "VFC",
    "SC Victoria '04",
    "VV Vierpolders",
    "CS Vitesse Delft",
    "FC Vlotbrug",
    "RVV VOB",
    "RC & VV VOC",
    "SV Vogelenzang",
    "SV Voorschoten '97",
    "Voorwaarts RSC",
    "KRSV Vredenburch",
    "HSV VUC",
    "VVAC",
    "VVGZ",
    "VVOR",
    "VVSB",
    "SCS Wanica Star",
    "SV Warmunda",
    "SV Wassenaar",
    "SV Wateringse Veld Kranenburg",
    "SV WCR",
    "VV WDS",
    "HVV Te Werve",
    "RKVV Westlandia",
    "VV WFB",
    "VV Wieldrecht",
    "VV WIK",
    "VV Wilhelmus",
    "SV Wippolder",
    "VV Woubrugge",
    "XerxesDZB",
    "ZBC '97",
    "ZBVH",
    "RCSV Zestienhoven",
    "SV Zevenhoven",
    "VV Zinkwegse Boys",
    "FC Zoetermeer",
    "VV Zuidland",
    "VV Zwaluwen",
    "VV Zwammerdam",
    "CSV Zwarte Pijl",
    "VV Zwartewaal",
    "VV De Zwerver",
    "CVV Zwervers",
    "IJVV De Zwervers",
    "VV Diever",
    "Elper Boys",
    "SV Halen",
    "Hermes AVK",
    "VV Hijker Boys",
    "VV Hunso",
    "VV Minjak",
    "SC Oranje (Schoonebeek)",
    "VV Oring",
    "VV THEO",
    "SV Wapse",
    "SV Almere",
    "BCV",
    "VV Bergum",
    "Bolswardia",
    "VV Boyl",
    "CAB",
    "CSL",
    "RKVV Friso",
    "VV Haulerwijk",
    "VV Harlingen",
    "ZVV Haulerwijkse Boys",
    "VV De Kooi",
    "VV Leeuwarden",
    "OZC",
    "RES",
    "Robur Harlingen",
    "VV Rood Geel",
    "VV Trynwâldster Boys",
    "VV Trynwâlden",
    "VV De Westhoek",
    "VOG",
    "AAC",
    "SV Aerdt",
    "VV Baakse Boys",
    "AAC Altforst",
    "Arnhem",
    "CVV Avanti Twello",
    "AVW",
    "AV Cranevelt",
    "SV Culemborg '67",
    "Berghse Boys",
    "VV Brakel",
    "BVH",
    "SV Carvium",
    "CVVA",
    "SV Dinxperlo",
    "DZSV",
    "SC Eibergen",
    "Eendracht (Nijmegen)",
    "VV Erica '76",
    "ESCA/VC",
    "EVC'94",
    "VV EWV",
    "Fortitudo",
    "FC Fortuna Elten 1910",
    "VV Gazelle Nieuwland",
    "Gelria",
    "Giro",
    "GOVA",
    "Hertog Hendrik",
    "Humanitas",
    "HVG",
    "Marhaba",
    "SV Maurik",
    "RKSV Meerwijk",
    "MvR",
    "NDT",
    "VV Noviomagum",
    "Nijmeegse Boys",
    "OAB",
    "ODO",
    "VV Olympia",
    "OZOD",
    "SC PGEM",
    "Plattenburger Boys",
    "NVV Nijmegen",
    "RKJC",
    "Roode Duivels",
    "Sempri Avanti",
    "RKVV Sint Jan",
    "Sint Joris",
    "SKVW",
    "Spatram",
    "VV SpijkVooruit",
    "SSSE",
    "SV Steenderen",
    "VV Stokkum",
    "SVD '98",
    "VV TGB",
    "SV V en K Twello",
    "VIJDO",
    "VVL",
    "WCA",
    "WHcZ",
    "VV Winterswijk",
    "Wivos",
    "WVC",
    "VV Zaltbommel",
    "VV Zeddam",
    "VV Zuilichem",
    "ZVV Zutphania",
    "SV Zutphen",
    "VV Astrea",
    "VV Bedum",
    "VV Boerakker",
    "CSVH",
    "CVVB",
    "Eems Boys",
    "VV Hoogkerk",
    "VV Leek Rodenburg",
    "VV Macedonie",
    "SV Maluku",
    "VV Neptunia",
    "VV Paddepoel",
    "SGVV '07",
    "SVMH",
    "VV Tolbert",
    "UVV '70",
    "VV Wagenborgen",
    "SV Zeester",
    "RKVV Almania",
    "VV Armada",
    "VV Banholtia",
    "VV Beegden",
    "SC Biesland",
    "RKVV Buchten",
    "SC Brachterbeek",
    "BVC '28",
    "SC Caberg",
    "RKVV Doenrade",
    "VV Grathem",
    "RKSV Griendtsveen",
    "RKVV Heel",
    "SV Heerlen",
    "Heerlen Sport",
    "VV Holtum",
    "SV Höngen",
    "KOC",
    "RKVV Kolonia",
    "Klimmania TC",
    "SV Limburgia",
    "RKVV Maasbracht",
    "RKVV Mariarade",
    "SV Meerlo",
    "Megacles",
    "Mheerder Boys",
    "SV Moesel",
    "MSP '03",
    "MSVM",
    "RKVV Obbicht",
    "VV Passart",
    "Quick Boys '31",
    "RKSV Rapid",
    "Reymerstokse Boys",
    "RKBSV",
    "RKDFC",
    "RKONS",
    "RKSVW",
    "VV SCKR-Ransdaal",
    "RKVV Sint Odiliënberg",
    "VV Sittard Oost",
    "SSOC",
    "RKVV Stadbroek",
    "VV Standaard",
    "Swolgense Boys",
    "RKVV Thorn",
    "VV TOP '27",
    "Treebeek Sport '35",
    "VfR Tüddern",
    "RKSV Venlo",
    "VV Vesta",
    "FC Viktoria Schalbruch 1919",
    "FC Vinkenslag",
    "VKC'89",
    "VV Valkenburgse Boys",
    "FC Wanderlust 1920 Süsterseel",
    "SV Wanssum",
    "Wit-Zwart '32",
    "WVV '28",
    "VV Breda",
    "ESV",
    "FSV",
    "FC De Geeren",
    "GFC '93",
    "RKSV Helenaveen",
    "Herptse Boys",
    "SV Heusden",
    "JPS",
    "VV Kaaise Boys",
    "SV Nevelo",
    "RKSV Oisterwijk",
    "SET",
    "VV De Spechten",
    "SC St. Hubert",
    "RKSV Taxandria",
    "TVC '39",
    "SV Triborgh",
    "VVS Eindhoven",
    "De Willy's",
    "WVVZ",
    "ZPR '84",
    "ADW",
    "VV AGT",
    "Arbeiders Sport Vereniging Archipel",
    "VV Atlas",
    "SV Bijlmer",
    "HFC Bloemenkwartier 1921",
    "DCO",
    "DEK",
    "DFS Alkmaar",
    "DWG/Rombout",
    "DWSV ‘61",
    "ASV DWV",
    "SC De Eland",
    "EDW",
    "VV Flamingo",
    "ASV De Germaan",
    "CSV De Geuzen",
    "ASV Go Ahead'18",
    "Gold Stars/SNA",
    "HFC Haarlem",
    "HEDW",
    "Hellas Sport Combinatie",
    "HFC Helder",
    "Hortus",
    "FC Huiswaard",
    "Inter Heemskerk",
    "JVVO",
    "HFC Kennemerland",
    "Kismet '82",
    "KSJB",
    "Madjoe",
    "De Meerboys",
    "Meerboys-A",
    "VV MFC",
    "ASV Middenmeer",
    "NEC ‘75",
    "SC Nieuwendam",
    "SC Orient",
    "AVV OVVO",
    "P en T",
    "RK PSCK",
    "PVWA",
    "RAP",
    "VV Ripperda",
    "SV Robinhood",
    "VV Schagen",
    "Sint Louis",
    "Sint-Nicolaas Lyceum",
    "SC Sloterpark/AGS",
    "Sporting Maroc",
    "VV SRC",
    "SV Toudgha",
    "FC Türkiyemspor",
    "RKSV TYBB",
    "ASV Vespucci",
    "De Volewijckers",
    "RKASV Wilskracht",
    "Wilskracht/SNL",
    "WGW",
    "Wilhelmina Vooruit",
    "VV Young Boys",
    "ASC Xanthos",
    "VVZ Zaandam",
    "HVV de Zebra's",
    "ZVV Zilvermeeuwen",
    "ZPC",
    "ASVO",
    "C.S.V. De CJV-ers",
    "Sportclub Denekamp",
    "SV Dinkelland",
    "DOS '19",
    "DVO '71",
    "De Eversberg",
    "HSA",
    "SV Nijverdal",
    "SV Omhoog",
    "OSV '31",
    "SV Rietvogels",
    "VV Rijssen Vooruit",
    "RKSV",
    "SOS",
    "Tilligte SV",
    "VV Vesos",
    "WVV Wierden",
    "VV CDN",
    "VV Dalto",
    "VV DOS",
    "VV Faja Lobi",
    "USV Holland",
    "KDS",
    "v.v. Montfoort",
    "VV MSV '19",
    "VV Nijenrodes",
    "SCNU",
    "Stichtse Boys",
    "VV Utrecht",
    "CSV Vitesse",
    "Yasamspor",
    "Zwaluwen Vooruit",
    "VV Axel",
    "AZVV",
    "SV Dreischor",
    "VV MEVO",
    "VV Zierikzee",
    "VV Zonnemaire",
    "HVV De Adelaars",
    "ADS Den Haag",
    "RVV AGE",
    "AVS-Germinal",
    "Activitas",
    "VV Anadolu",
    "HVV Archipel",
    "GS Azzuri",
    "VV Belvedère",
    "BIZON (BInnenlandse Zaken ONtspanning)",
    "FC Boszoom",
    "VV Centro Português",
    "HVV Cromvliet",
    "DEVJO",
    "VV DMC",
    "DOS'32",
    "DORR (Door Oefening Razend Rap)",
    "DOTO",
    "VV DRGS",
    "SV Duinoord",
    "Dynamo '67",
    "EDS",
    "ESDO (Eendrachtig Samenspel Doet Overwinnen)",
    "PVV Excelsior Pernis",
    "VV GGK",
    "'s-Gravenzandse SV",
    "'s Gravenzandse VV",
    "Groen Wit Rotterdam",
    "GDCPH (Gruppo Desportivo Casa Portuguesa Haja)",
    "RSV HION",
    "RSV De Flamingo's",
    "Groen Wit ‘58",
    "SC GSC",
    "VV Hoek van Holland",
    "VV Hoekse Boys",
    "Holland Sport ‘32",
    "VV JAC (Jeugdkring Ambtenaren Combinatie)",
    "KFC ‘71",
    "RKSV JuVentaS",
    "HSV Kranenburg",
    "VV Leiden",
    "VV LenS (Lenig en Snel)",
    "VV Maasstraat",
    "HSV Marathon",
    "VV Monster",
    "Nationale Nederlanden",
    "SC Neptunus",
    "SCV Neta Dall",
    "NLS (Na Lering Sterker)",
    "RVV Noorderkwartier",
    "ODS",
    "VV Oegstgeest",
    "OSC (Oosterboys S.V.T. Combinatie)",
    "HVV De Ooievaars",
    "Oranje Blauw",
    "VV Oranjeplein",
    "Oranjeplein-Postduiven",
    "Hvv Paraat",
    "PDK (Procureurs en Deurwaarders Klerken)",
    "VV PEC",
    "PEC Den Haag (Post Energie Combinatie)",
    "PGS (Personeel Gemeente Secretarie)",
    "SV Polanen",
    "Postalia",
    "LVV De Postduiven",
    "PVS (Personeels Vereniging Staatsdrukkerij)",
    "VV PZH (Provincie Zuid Holland)",
    "VV RAVA",
    "Real Parbo",
    "FC Rijnland",
    "RVV Rijswijk",
    "VV Robin Hood",
    "RVC (Rijswijkse Voetbal Club)",
    "HSV SOA (Samenspel Overwint Alles)",
    "RVV Schiebroek '94",
    "Hvv Spoorwijk",
    "SCSV De Ster",
    "SV SVLY",
    "TAMUVONA (Telegraaf Amusements Vereniging Ontspanning Na Arbeid)",
    "TEDO (Techniek en Enthousiasme Doen Overwinnen)",
    "VV Texas DZ",
    "VSV TONEGIDO",
    "VV UDO",
    "RKVV De Valkeniers",
    "VV VDS (Vooruitgang Door Samenspel)",
    "VIOS (Vooruitgang Is Ons Streven)",
    "SC Voorne",
    "VVP (Voetbal Vereniging Pancratius)",
    "VV Waddinxveen",
    "HSV Westerkwartier",
    "RKSV Wit Blauw",
    "HSV Wilsonmeters",
    "WRW",
    "VV WSE",
    "HSV WVS (Wilskracht Voor Spierkracht)",
    "VV Zwart Blauw",
    "VV De Zwarte Schapen",
    "Zwart-Wit'28",
    "Lijst van KNVB clubs op rsssf.com"
  ]